record:
    resource: "@RecordBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

songs:
        resource: "@RecordBundle/Controller"
        type:     annotation