# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     app.markdown_transformer:
         class: RecUp\RecordBundle\Service\MarkdownTransformer
         arguments: ['@markdown.parser', '@doctrine_cache.providers.my_markdown_cache']
     app.markdown_extension:
         class: RecUp\RecordBundle\Twig\MarkdownExtension
         tags:
            - { name: twig.extension }
         autowire: true
     twig_asset_version_extension:
        class: RecUp\RecordBundle\Twig\AssetVersionExtension
        arguments: ["%kernel.root_dir%"]
        tags:
          - { name: twig.extension }
     recup_menu_voter_request:
        class: RecUp\UserBundle\Menu\RequestVoter
        arguments: ["@request_stack"]
        tags:
          - { name: knp_menu.voter }
     recup_current_user:
        class: RecUp\UserBundle\Service\FindCurrentUser
        arguments: ['@security.token_storage', '@doctrine.orm.entity_manager']
     app.user_voter:
        class: RecUp\UserBundle\Security\UserVoter
        tags:
          - { name: security.voter }
     twig_date_sort_extension:
          class: RecUp\RecordBundle\Twig\SortByDateExtension
          tags:
            - { name: twig.extension }
#        public: false
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
