<?php
/**
 * Created by PhpStorm.
 * User: jkr
 * Date: 6/2/2016
 * Time: 11:19 AM
 */

namespace RecUp\UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UserFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//       need to build the form here for the UserController.
    }
    
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}